### ISSUE TITLE
.webService() error 500

### ISSUE THREAD

**Issue by arek125** [Aymkdn/SharepointPlus#51]
Hi, i'm trying to use new .webService() function like this (Sharepoint 2010): 
```
$SP().webService({ 
  service:"UserGroup",
  operation:"RemoveUserFromGroup",
  properties:{
    groupName:"TestGroup",
    userLoginName:"DOMAIN\\login"
  }
}).then(function(response) {
  console.log(response);
});
```
and it's end up with "..._vti_bin/UserGroup.asmx 500 (Internal Server Error)", what can be wrong ? I also tested other opertions from usergrup service with the same result.

**Comment by Aymkdn** [comment]
I can see the server returns `Server did not recognize the value of HTTP Header SOAPAction: http://schemas.microsoft.com/sharepoint/soap/RemoveUserFromGroup.`

It looks like the SOAP URL for this web service is `http://schemas.microsoft.com/sharepoint/soap/directory/` and not `http://schemas.microsoft.com/sharepoint/soap/`....

I'll add a `soapURL` option to handle thiscase. It'll be fixed in the next release (v4.1).

In the meantime you can replace your `webService` with the code from https://github.com/Aymkdn/SharepointPlus/blob/development-v4.1/sharepointplus-4.1.js#L516

And to use it:
```javascript
$SP().webService({ 
  service:"UserGroup",
  operation:"RemoveUserFromGroup",
  soapURL:"http://schemas.microsoft.com/sharepoint/soap/directory/",
  properties:{
    groupName:"Group",
    userLoginName:"domain\\user"
  }
}).then(function(response) {
  console.log("OK => ",response)
}, function(error) { console.log("Error => ",error) });
```

**Comment by micuentadecasa** [comment]
I tried the former code and version 4.1. still fails and give 500 error.

**Comment by Aymkdn** [comment]
> I tried the former code and version 4.1. still fails, it hangs the browser.

Please provide your code as well as the response returned from the server.

**Comment by micuentadecasa** [comment]
I have downloaded the https://github.com/Aymkdn/SharepointPlus/blob/development-v4.1/sharepointplus-4.1.js#L516 file, and used this code

$SP().webService({ 
  service:"UserGroup",
  operation:"RemoveUserFromGroup",
  soapURL:"http://schemas.microsoft.com/sharepoint/soap/directory/",
  properties:{
    groupName:"Group",
    userLoginName:"domain\\user"
  }
}).then(function(response) {
  console.log("OK => ",response)
}, function(error) { console.log("Error => ",error) });

and what I get is browser hanged

**Comment by Aymkdn** [comment]
I've just tried in IE11, Firefox and Chrome, and it worked.

If you use SP2013 or higher, the `userLoginName` should be `i:0#.w|domain\\user`.

See below the code I used:
```javascript
$SP().webService({
  service:"UserGroup",
  operation:"RemoveUserFromGroup",
  soapURL:"http://schemas.microsoft.com/sharepoint/soap/directory/",
  properties:{
    groupName:"Global Owners", // name of my group
    userLoginName:"i:0#.w|corporate\\aym_kdn"
  }
}).then(function(response) {
  console.log("OK => ",response)
}).catch(function(error) { console.log("Error => ",error) })
```

**Comment by micuentadecasa** [comment]
tried and still hangs, sorry.

**Comment by Aymkdn** [comment]
The problem is problaly coming from your code.

You'll have to debug by yourself: create a simple page where you call SharepointPlus and with only the code above. Nothing else. Try it and see the result.

I won't help further as it doesn't seem to be related to SharepointPlus.

**Comment by micuentadecasa** [comment]
I think is not my code, if I put your code on the page then it hangs, and I put it on first position. Should be something else. Anyway I've found an alternative so is not a hurry.
